### PR TITLE
VX3: Use O3EDtcList Codec for 257-266

### PR DESCRIPTION
**Pull request by achgut**

### CODE REVIEW

**Comment by jwende** [comment]
I would recommend to wait for O3EList - this is more generic… 
Cheers
Joerg

**Comment by MyHomeMyData** [comment]
I agree to Joerg, it's better to wait for O3EList.
Jürgen

**Comment by philippoo66** [comment]
O3EList is in the feature branch 'list' and in 'feature-universallist' branch an is working great :-)

**Comment by achgut** [comment]
OK for me. Did not realize that you are working on a new function. 
Will close the pull request.

**Comment by philippoo66** [comment]
Moin @achgut ! there is a completley new version in develop branch. the new O3EList codec is contained and applied. also there is one general did/codec list an overlays for the individual devices. much easyer to control... ;-) don't hesitate to have a look and try! ;-)

**Comment by achgut** [comment]
@philippoo66 Already running. Looks good. Thank you.

**Pull request closed without merging**
