### PR TITLE
Update datapoints

### PR DESCRIPTION
**Pull request by SanMiggel**
- circulation pump (best guess and tested)
- energy input/output statistics (best guess and tested)

### CODE REVIEW

**Comment by jwende** [comment]
Thanks for your effort - I was just working on these datapoints as we speak ... 
I've created an O3EArray datatype - so I could describe the energy consumption datapoints better:

1294 : O3EComplexType(124, "EnergyConsumptionCentralHeatingMonthMatrix",[O3EArray(62, "CurrentMonth",[O3EInt16(2,"DailyUse")], arraylength = 31), O3EArray(62, "LastMonth", [O3EInt16(2,"DailyUse")], arraylength = 31)]),

I made also an update for datapoint 497
497 : O3EComplexType(5, "DomesticHotWaterCirculationPumpMode",[O3EByteVal(1, "Mode"), O3EByteVal(1, "HygenieActive"), O3EByteVal(1, "HeatingActive"), O3EByteVal(1, "Unknown"), O3EByteVal(1, "Cycles")]),

Result:
python3 Open3Eclient.py -c can0 -dev vcal -r 497
{'Mode': 4, 'HygenieActive': 0, 'HeatingActive': 0, 'Unknown': 0, 'Cycles': 3}

**Comment by jwende** [comment]
I was looking over your PR  - one comment first: you made a lot of changes and that required a lot of typing :-D. 
Some of the models are incomplete - all monthly datapoints contain data for the current and the previous month (2 bytes per day)
same for the yearly datapoints - the current year and previous year (4 bytes per month)  
... small effort to update the datapoints (mainly copy and paste)
but I'm not sure which way would be better - complex type as you did or my array approach - so I would wait for more input from other developers or users.

**Comment by SanMiggel** [comment]
> Thanks for your effort - I was just working on these datapoints as we speak ... I've created an O3EArray datatype - so I could describe the energy consumption datapoints better:
> 
> 1294 : O3EComplexType(124, "EnergyConsumptionCentralHeatingMonthMatrix",[O3EArray(62, "CurrentMonth",[O3EInt16(2,"DailyUse")], arraylength = 31), O3EArray(62, "LastMonth", [O3EInt16(2,"DailyUse")], arraylength = 31)]),

Ah, I didnt realize that it is also data from the previous month. Your solution is much better then.

> I made also an update for datapoint 497 497 : O3EComplexType(5, "DomesticHotWaterCirculationPumpMode",[O3EByteVal(1, "Mode"), O3EByteVal(1, "HygenieActive"), O3EByteVal(1, "HeatingActive"), O3EByteVal(1, "Unknown"), O3EByteVal(1, "Cycles")]),
> 
> Result: python3 Open3Eclient.py -c can0 -dev vcal -r 497 {'Mode': 4, 'HygenieActive': 0, 'HeatingActive': 0, 'Unknown': 0, 'Cycles': 3}

I tried it by reverse enginieering. Where did you get that info?

Seems my attempt is rather incomplete. So lets wait for some more comments.

**Comment by jwende** [comment]
A good source: 
image
You may find a link in the Viessmann customer forum ...
Cheers
J.

**Comment by jwende** [comment]
Based on your approach:
        ```
1294 : O3EComplexType(124, "EnergyConsumptionCentralHeatingMonthMatrix",[
            O3EList(64, "CurrentMonth",[O3EInt16(2, "1"), O3EInt16(2, "2"), O3EInt16(2, "3"), O3EInt16(2, "4"), O3EInt16(2, "5"), O3EInt16(2, "6"), O3EInt16(2, "7"), O3EInt16(2, "8"), O3EInt16(2, "9"), O3EInt16(2, "10"), O3EInt16(2, "11"), O3EInt16(2, "12"), O3EInt16(2, "13"), O3EInt16(2, "14"), O3EInt16(2, "15"), O3EInt16(2, "16"), O3EInt16(2, "17"), O3EInt16(2, "18"), O3EInt16(2, "19"), O3EInt16(2, "20"), O3EInt16(2, "21"), O3EInt16(2, "22"), O3EInt16(2, "23"), O3EInt16(2, "24"), O3EInt16(2, "25"), O3EInt16(2, "26"), O3EInt16(2, "27"), O3EInt16(2, "28"), O3EInt16(2, "29"), O3EInt16(2, "30"), O3EInt16(2, "31")]),
            O3EList(64, "LastMonth",[O3EInt16(2, "1"), O3EInt16(2, "2"), O3EInt16(2, "3"), O3EInt16(2, "4"), O3EInt16(2, "5"), O3EInt16(2, "6"), O3EInt16(2, "7"), O3EInt16(2, "8"), O3EInt16(2, "9"), O3EInt16(2, "10"), O3EInt16(2, "11"), O3EInt16(2, "12"), O3EInt16(2, "13"), O3EInt16(2, "14"), O3EInt16(2, "15"), O3EInt16(2, "16"), O3EInt16(2, "17"), O3EInt16(2, "18"), O3EInt16(2, "19"), O3EInt16(2, "20"), O3EInt16(2, "21"), O3EInt16(2, "22"), O3EInt16(2, "23"), O3EInt16(2, "24"), O3EInt16(2, "25"), O3EInt16(2, "26"), O3EInt16(2, "27"), O3EInt16(2, "28"), O3EInt16(2, "29"), O3EInt16(2, "30"), O3EInt16(2, "31")]),
        ]),
```

**Comment by jwende** [comment]
{
    'CurrentMonth': {
        '1': 48.0,
        '2': 68.0,
        '3': 49.7,
        '4': 0.0,
        '5': 0.0,
        '6': 0.0,
        '7': 0.0,
        '8': 0.0,
        '9': 0.0,
        '10': 0.0,
        '11': 0.0,
        '12': 0.0,
        '13': 0.0,
        '14': 0.0,
        '15': 0.0,
        '16': 0.0,
        '17': 0.0,
        '18': 0.0,
        '19': 0.0,
        '20': 0.0,
        '21': 0.0,
        '22': 0.0,
        '23': 0.0,
        '24': 0.0,
        '25': 0.0,
        '26': 0.0,
        '27': 0.0,
        '28': 0.0,
        '29': 0.0,
        '30': 0.0,
        '31': 0.0
    },
    'LastMonth': {
        '1': 11.6,
        '2': 10.4,
        '3': 15.7,
        '4': 11.8,
        '5': 12.1,
        '6': 10.4,
        '7': 13.0,
        '8': 19.1,
        '9': 17.4,
        '10': 22.3,
        '11': 25.4,
        '12': 23.8,
        '13': 13.9,
        '14': 18.5,
        '15': 20.4,
        '16': 34.7,
        '17': 31.1,
        '18': 21.1,
        '19': 19.8,
        '20': 30.0,
        '21': 47.5,
        '22': 33.5,
        '23': 36.7,
        '24': 47.6,
        '25': 49.3,
        '26': 48.8,
        '27': 52.1,
        '28': 48.8,
        '29': 42.0,
        '30': 0.0,
        '31': 0.0
    }
}

**Pull request merged**
